// Generated by LiveScript 1.3.1
var layers, id, opts, ext;
L.SINICA = {};
L.SINICA.TileLayer = L.TileLayer.extend({
  options: {
    attribution: '© <a target="_target" href="http://gis.sinica.edu.tw/">Sinica</a>'
  },
  initialize: function(options){
    options = L.Util.setOptions(this, options);
    return L.TileLayer.prototype.initialize.call(this, options.url);
  },
  getTileUrl: function(tilePoint){
    return L.Util.template(this._url, L.extend({
      s: this._getSubdomain(tilePoint),
      z: 17 - tilePoint.z,
      x: tilePoint.x,
      y: tilePoint.y
    }, this.options));
  }
});
layers = {
  "1956_Landuse": {
    name: "1956-臺灣土地利用及林型圖",
    ext: 'png'
  },
  "AM50K_1944": {
    name: "1944-美軍地形圖-1:50,000",
    ext: 'png'
  },
  "AMCityPlan_1945": {
    name: "1945-美軍繪製臺灣城市地圖",
    maxZoom: 17,
    minZoom: 12,
    ext: 'png'
  },
  "JM100K_1905": {
    name: "1905-日治臺灣圖-1:100,000"
  },
  "JM200K_1897": {
    name: "1897-日治臺灣假製二十萬分一圖-1:200,000"
  },
  "JM200K_1932": {
    name: "1932-二十萬分一帝國圖(臺灣部分)"
  },
  'JM20K_1904': {
    name: "1904-日治臺灣堡圖(明治版)-1:20,000",
    ext: 'jpg'
  },
  "JM20K_1921": {
    name: "1921-日治臺灣堡圖(大正版)-1:20,000",
    ext: 'jpg'
  },
  "JM25K_1921": {
    name: "1921-日治地形圖-1:25,000"
  },
  "JM25K_1944": {
    name: "1944-日治地形圖(航照修正版)-1:25,000"
  },
  "JM300K_1924": {
    name: "1924-日治臺灣全圖(第三版)-1:300,000",
    ext: 'jpg'
  },
  "JM300K_1939": {
    name: "1939-日治臺灣全圖(第五版)-1:300,000",
    ext: 'png'
  },
  "JM400K_1899": {
    name: "1899-日治臺灣全圖-1:400,000"
  },
  "JM500K_1936": {
    name: "1936-五十萬分一輿地圖(臺灣部分)-1:500,000"
  },
  "JM50K_1916": {
    name: "1916-日治蕃地地形圖-1:50,000",
    ext: 'jpg'
  },
  "JM50K_1920": {
    name: "1920-日治地形圖(總督府土木局)-1:50,000",
    maxZoom: 16,
    minZoom: 5
  },
  "JM50K_1924": {
    name: "1924-日治地形圖(陸地測量部)-1:50,000",
    ext: 'jpg'
  },
  "TM100K_1987": {
    name: "1987-臺灣地形圖-1:100,000"
  },
  "TM25K_1989": {
    name: "1989-臺灣經建1版地形圖-1:25,000",
    ext: 'jpg'
  },
  "TM25K_1993": {
    name: "1993-臺灣經建2版地形圖-1:25,000",
    ext: 'jpg'
  },
  "TM25K_2001": {
    name: "2001-臺灣經建3版地形圖-1:25,000",
    ext: 'jpg'
  },
  "TM25K_2003": {
    name: "2003-臺灣經建4版地形圖-1:25,000",
    ext: 'jpg'
  },
  "TM50K_1956": {
    name: "1956-臺灣地形圖-1:50,000",
    ext: 'jpg'
  },
  "TM50K_1990": {
    name: "1990-臺灣經建1版地形圖-1:50,000"
  },
  "TM50K_1996": {
    name: "1996-臺灣經建2版地形圖-1:50,000"
  },
  "TM50K_2002": {
    name: "2002-臺灣經建3版地形圖-1:50,000"
  },
  "Taipei_aerialphoto_1945": {
    name: "美軍航照影像(1945/6/17攝)",
    ext: 'jpg'
  },
  'Tainan_1875B': {
    name: '1875-臺灣府城並安平海口圖',
    minZoom: 12,
    MaxZoom: 18
  },
  'Tainan_1895': {
    name: '1895-日治五萬分之一地形圖_臺南地區'
  },
  'Tainan_1895c': {
    name: '1895-日治五萬分之一地形圖_臺南地區'
  },
  'Tainan_1896': {
    name: '1896-臺南城圖'
  },
  'Tainan_1900': {
    name: '1900-臺南城圖'
  },
  'Tainan_1907B': {
    name: '市區改正臺南市街全圖(1907)'
  },
  'Tainan_1911': {
    name: '臺南市區改正計畫圖(1911)'
  },
  'Tainan_1915': {
    name: '臺南市全圖(1915)'
  },
  'Tainan_20K_1917': {
    name: '1917-臺南市全圖'
  },
  'Tainan_1918': {
    name: '臺南市全圖(1918)'
  },
  'Tainan_1920': {
    name: '臺南市全圖(1920)'
  },
  'Tainan_1924B': {
    name: '臺南市全圖(1924)'
  },
  'Tainan_1935': {
    name: '臺南市街圖(1935)'
  },
  'Tainan_1936': {
    name: '臺南職業別明細圖(1936)',
    ext: 'jpg'
  },
  'Tainan_1939': {
    name: '臺南市街略圖(1939)'
  },
  'Tainan_1945': {
    name: '臺南市新舊街路名圖(1945)'
  },
  'Tainan_1946': {
    name: '臺南市全圖(1946)'
  },
  'Tainan_1951': {
    name: '安平港海圖(1951)'
  },
  'Tainan_1959': {
    name: '臺南市街圖(1959)'
  },
  'Tainan_1971': {
    name: '臺南市街詳細圖(1971)'
  },
  'Tainan_1974': {
    name: '1974-臺南市全圖'
  },
  'Tainan_1982': {
    name: '1982-臺南市圖'
  },
  'Tainan_1984': {
    name: '1984-臺南市街圖'
  },
  'Tainan_1986': {
    name: '1986-臺南市都市計畫圖(藍曬)'
  },
  'Tainan_1K_2010': {
    name: '2010-臺南市航照影像'
  }
};
L.SINICA.TileLayers = [];
for (id in layers) {
  opts = layers[id];
  ext = opts.ext != null && opts.ext || 'png';
  opts['url'] = opts.url != null && opts.url || "http://gis.sinica.edu.tw/googlemap/" + id + "/{z}/{x}/IMG_{x}_{y}_{z}." + ext;
  L.SINICA.TileLayers[id] = L.SINICA.TileLayer.extend({
    name: opts.name,
    options: opts
  });
}