// Generated by LiveScript 1.2.0
L.SINICA = {};
L.SINICA.WMS = L.TileLayer.WMS.extend({
  _url: 'http://gis.sinica.edu.tw/tileserver/wmts',
  defaultWmsParams: {
    service: 'WMS',
    request: 'GetMap',
    version: '1.1.0',
    layers: '',
    styles: '',
    format: 'image/jpeg',
    transparent: true
  },
  options: {
    attribution: '© <a target="_target" href="http://gis.sinica.edu.tw/">中央研究院地理資訊科技研發與應用</a>'
  },
  initialize: function(options){
    var wmsParams, i;
    this.defaultWmsParams['layers'] = this.layerid;
    wmsParams = L.extend({}, this.defaultWmsParams);
    for (i in options) {
      if (this.options[i] == null && i !== 'crs') {
        wmsParams[i] = options[i];
      }
    }
    options = L.setOptions(this, options);
    wmsParams.width = wmsParams.height = options.tileSize * (options.detectRetina && L.Browser.retina ? 2 : 1);
    return this.wmsParams = wmsParams;
  }
});
L.SINICA.TM25K_2001 = L.SINICA.WMS.extend({
  name: '2001-臺灣經建3版地形圖-1:25,000',
  layerid: 'TM25K_2001'
});